config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
    }


	constraints(host: /^(?!www\.)/i) do
	    match '(*any)' => redirect { |params, request|
	      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
	    }, :via => :all
 	end

	root to: 'pages#home'

	match "/404", :to => "errors#not_found", :via => :all
	match "/422", :to => "errors#unacceptable", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all

	get '/sitemap.xml' => 'sitemaps#index', :format => 'xml', :as => :sitemap

	get 'robots.:format' => 'pages#robots'
	get 'mentions-legales' => 'pages#mentions_legales'


	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]

	resources :blogs do
		member do
            put "like" => "blogs#upvote"
            put "unlike" => "blogs#unvote"
        end
        resources :comments, :only => [:index, :new, :edit, :create, :update, :destroy] 
	end

	get 'creation-site-internet' => 'services#creation_site_internet'
	get 'referencement' => 'services#referencement'

	mount PolicyManager::Engine => "/policies"

	dynamic_error_pages
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:creation_site_internet, :referencement]
  skip_after_action :verify_authorized, only: [:creation_site_internet, :referencement]

  def creation_site_internet
  end

  def referencement
  end
end

app/views/services/creation_site_internet.html.erb
<script type="application/ld+json" nonce=<%= request.content_security_policy_nonce %>>
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Accueil",
    "item": "<%= root_url %>"
  },{
    "@type": "ListItem",
    "position": 2,
    "name": "Création de site internet",
    "item": "<%= contacts_url %>"
  }]
}
</script>

<% content_for :meta_title, "Création de site - Agence marketing web Aix en provence" %>
<% content_for :meta_description, "Créez votre site internet en accord avec votre image pour attirez les prospects | Dataweb Univers : agence de marketing web à aix en provence – Théo Dumez" %>
<% content_for :meta_robots, "index" %>

<%= render "shared/navbar" %>

<!-- Banner -->

<div class="banner relative index1">
    <div class="w50 flex-center index1">
		<div class="banner-text">
			<div class="rotating-text mt-4">
				<h1 class="rb-55 teel h1 text-center">Création de site internet</h1>
			    <p class="khaki-font font-30 rt-80 text-center mx-auto rl-10">
			    	Site vitrine / e-commerce /<br>
			    	logiciel web
			    </p>
			</div>
		</div>
	</div>
    <div class="flex-center index1 img-banner-section">
    	<%= image_tag(asset_path('creation-site-internet.svg'), alt: 'agence marketing web Aix en Provence creation-site-internet', class: 'img-banner3') %>
    </div>
</div>

<!-- Banner-end -->

<div class="site flex-center flex-column mb-200 relative mt-5" data-aos="zoom-in-up">
	<h2 class="h2 text-left black index1">Création de votre site internet</h2>
	<p class='mb-100 budget teel index1 mb-5'>Un besoin, une solution adaptée, un budget maitrisé.</p>
	<div class="flex-row flex-around w100 index1">
		<div class="site-column relative text-center flex-center" data-aos="fade-up-right">
			<p class="index1 black-olive font-25px">Identité graphique Création + Refonte</p>
			<%= image_tag(asset_path('Ellipse-4.png'), alt: 'agence marketing web Aix en Provence : Identité graphique Création + Refonte', class: 'absolute index0 cercle-site2') %>
		</div>
		<div class="site-column relative text-center flex-center" data-aos="fade-up">
			<p class="index1 black-olive font-25px">Visibilité Google Référencement naturel (SEO) & Google Ads (SEA)</p>
			<%= image_tag(asset_path('Ellipse-4.png'), alt: 'agence marketing web Aix en Provence : Visibilité Google Référencement naturel (SEO) & Google Ads (SEA)', class: 'absolute index0 cercle-site3') %>
		</div>
		<div class="site-column relative text-center flex-center" data-aos="fade-up-left">
			<p class="index1 black-olive font-25px">Site sécurisé avec accès au back-office</p>
			<%= image_tag(asset_path('Ellipse-7.png'), alt: 'agence marketing web Aix en Provence : Site sécurisé avec accès au back-office', class: 'absolute index0 cercle-site2') %>
		</div>
	</div>
	<p class="mt-100 maquettage2 teel index1 text-center" data-aos="flip-left">Nous nous déplaçons dans toute la région d’Aix en Provence et des alentours pour étudier avec vous votre projet</p>
	<%= image_tag(asset_path('Ellipse-2.svg'), alt: 'développeur web', class: 'absolute index0 img-curve-left') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mb-100" data-aos="zoom-in-up">
	<h2 class="mb-5 h2 text-left black index1">Pourquoi créer un site internet ?</h2>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Le site web est aujourd’hui un incontournable dans votre communication sur Internet. Face à la croissance de la recherche en ligne, il est un outil marketing idéal pour <strong>attirer les prospects et les convertir en clients.</strong></p>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Aujourd’hui, ces derniers ne souhaitent plus « subir » la publicité. Ils veulent être <strong>séduits par du contenu innovant qui apporte de la valeur ajoutée.</strong></p>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Seul un site internet peut vous offrir de telles opportunités. Il contribue à votre visibilité, et votre e-réputation. Un professionnel présent sur le web est considéré comme sérieux. Il l’est d’autant plus si son site est <strong>propre, fonctionnel et design.</strong></p>
	<%= image_tag(asset_path('Ellipse-8.png'), class: 'absolute index-1 cercle-site5') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mt-200 mb-100" data-aos="zoom-in-up">
	<h2 class="mb-5 h2 text-left black index1">Un site en accord avec votre image</h2>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Chez DataWeb Univers, vous trouverez une équipe capable de répondre à l’ensemble de vos problématiques de communication web : l’affirmation de votre image au travers du design du site, de votre clientèle et de votre visibilité. </p>
	<p class="blue index1 letter-014" data-aos="flip-left">Nous abordons les choses sous un angle global en évaluant tous les leviers techniques (technologie liée au site web, SEO, SEA, remarketing, netlinking, etc.). Une fois un site mis en ligne, il faut l’entretenir et l’optimiser pour attirer du trafic de qualité.</p>
	<%= image_tag(asset_path('Ellipse-10.svg'), class: 'absolute index-1 img-curve-left4') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mt-200 mb-100 flex-between" data-aos="zoom-in-up">
	<div class="qu-est-ce-que-le-seo-text">
		<h2 class="mb-5 h2 text-left black index1">Devenez propriétaire de votre site</h2>
		<p class="black-olive index1 letter-014" data-aos="fade-right">Une fois livré, vous devenez propriétaire de votre site internet. Beaucoup d’agences vous proposent des locations longue durée sans option d’achat, pas nous. Par ailleurs, toutes nos technologies utilisées sont open-source.</p>
		<p class="blue index1 letter-014" data-aos="flip-left">A nos côtés, le produit livré pourra tout de même évoluer durablement dans le temps de manière indépendante.</p>
	</div>
	<%= image_tag(asset_path('referencement.png'), class: 'refrencement-img-page') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mb-200" data-aos="zoom-in-up">
	<h2 class="mb-5 h2 text-left black index1">Distinguez-vous sur le web !</h2>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Vous aimeriez vous aussi être différent, sortir du lot, faire valoir votre valeur ajoutée dans un monde numérique très concurrentiel ?</p>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Contactez-nous afin de vous aider, d’obtenir des réponses et des solutions personnalisées.</p>
	<%= image_tag(asset_path('Ellipse-8.png'), class: 'absolute index-1 cercle-site6') %>
</div>

<%= render "shared/footer" %>
<%= render 'cookies_eu/consent_banner'%>

app/views/services/referencement.html.erb
<script type="application/ld+json" nonce=<%= request.content_security_policy_nonce %>>
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Accueil",
    "item": "<%= root_url %>"
  },{
    "@type": "ListItem",
    "position": 2,
    "name": "Création de site internet",
    "item": "<%= contacts_url %>"
  }]
}
</script>

<% content_for :meta_title, "Référencement - Agence marketing web Aix en provence" %>
<% content_for :meta_description, "Référencement Naturel (SEO), Payant (SEA), boostez votre visibilité ! | Dataweb Univers : agence de marketing web à aix en provence – Théo Dumez" %>
<% content_for :meta_robots, "index" %>
<%= render "shared/navbar" %>

<!-- Banner -->

<div class="banner relative index1">
    <div class="w50 flex-center index1">
		<div class="banner-text">
			<div class="rotating-text mt-4">
				<h1 class="rb-55 teel h1 text-center">Référencement naturel et<br>payant ( SEO / SEA ) :</h1>
			    <p class="khaki-font font-30 rt-80 text-center rl-10">
			    	Augmentez votre visibilité sur<br>
			    	Google
			    </p>
			</div>
		</div>
	</div>
    <div class="flex-center index1 img-banner-section">
    	<%= image_tag(asset_path('referencement-SEO_SEA.svg'), alt: 'référencement naturel et payant ( SEO / SEA ) agence marketing web Aix en Provence', class: 'img-banner2') %>
    </div>
</div>

<!-- Banner-end -->

<div class="referencement flex-center flex-column background-img relative" data-aos="zoom-in-up">
	<div class="flex-start flex-row mt-4 flex-around index1">
		<%= image_tag(asset_path('referencement.png'), alt: 'agence marketing web Aix en Provence référencement', class: 'img-referencement mx-5 img-SEO') %>
		<div class="flex flex-column">
			<h2 class="mb-5 h2 text-left ml-5 black comment-title">
				Comment choisir une agence SEO ?
			</h2>
			<div class="referencement-text flex-start flex-row flex-around"  data-aos="zoom-in-left">
				<div class="referencement-column2 mx-5 text-center">
					<h3 class="h3">Stratégie d’entreprise</h3>
					<p class="taupe">Elle doit définir avec vous des objectifs clairs en adéquation avec votre stratégie d’entreprise.</p>
				</div>
				<div class="referencement-column2 mx-5 text-center">
					<h3 class="h3">Travail d’équipe et d’action</h3>
					<p class="taupe">il faut qu’il y ait une communication régulière et constructive entre l’agence et vous. C’est indispensable pour établir la confiance.</p>
				</div>
				<div class="referencement-column2 mx-5 text-center">
					<h3 class="h3"> Transparence des résultats</h3>
					<p class="taupe">Votre agence doit vous communiquer des reportings aussi complets et compréhensibles que possible autant pour ses actions que de ses résultats.</p>
				</div>
			</div>
		</div>
	</div>
	<%= image_tag(asset_path('background-curve.svg'), class: 'absolute t-14 w100 index0 img-curve') %>
</div>

<div class="qu-est-ce-que-le-seo ce-que-SEO index1 mx-auto relative mt-100 mb-100" data-aos="zoom-in-up">
	<h2 class="mb-5 h2 text-left black index1">Qu’est-ce que le SEO ?</h2>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Le SEO (Search Engine Optimization) est l’art d’améliorer le positionnement d’un site sur les moteurs de recherche pour augmenter son trafic et ses revenus.</p>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Son objectif est d’attirer vers vos pages web un trafic de qualité, susceptible de se convertir en prospects, puis en clients</p>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Ainsi, optimiser le référencement est un travail de précision. Il vous permet de capter l’attention de ceux qui sont intéressés par le type de services / de produits que vous proposez.</p>
	<p class="blue index1 letter-014" data-aos="flip-left">Ce trafic généré par le référencement Google a pour vocation d’être pérenne sur le long terme. Contrairement à une campagne publicitaire, le SEO continue d’attirer du trafic (et de produire des bénéfices) même lorsque vous ne l’optimisez plus.</p>
	<%= image_tag(asset_path('Ellipse-2.svg'), class: 'absolute index-1 img-curve-left2') %>
	<%= image_tag(asset_path('Ellipse-8.png'), class: 'absolute index-1 cercle-site4') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mt-200 mb-100" data-aos="zoom-in-up">
	<h2 class="mb-5 h2 text-left black index1">Notre philosophie</h2>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Nous étudions vos problématiques et analysons votre site. Quels sont vos acquis, quels points sont à améliorer et lesquels sont inexistants ? Nous nous assurons que tout soit fait pour satisfaire vos attentes et celles de votre cible.</p>
	<p class="black-olive index1 letter-014" data-aos="fade-right">Nous abordons les choses sous un angle global en évaluant tous les leviers techniques (technologie liée au site web, SEO, SEA, remarketing, linkbuilding, etc.). Une fois un site mis en ligne, il faut l’entretenir et l’optimiser pour attirer du trafic de qualité.</p>
	<p class="blue index1 letter-014" data-aos="flip-left">Que ce soit pour un projet partant de zéro, une refonte ou une optimisation d’un site déjà crée, les services que nous proposons sauront s’accorder à vos besoins ainsi qu’à votre budget.</p>
	<%= image_tag(asset_path('Ellipse-10.svg'), class: 'absolute index-1 img-curve-left3') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mt-200 mb-100 flex-between" data-aos="zoom-in-up">
		<h2 class="mb-5 h2 text-left black index1">Qu'est que le référencement naturel SEO on-site ?</h2>
		<p class="black-olive index1 letter-014" data-aos="fade-right">Le référencement naturel on-site regroupe l’architecture de votre site internet et les éléments de vos pages web:</p>
		<p class="black-olive index1 letter-014 ml-4" data-aos="fade-right">
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Les balises html (title, meta description, niveaux de titres Hn (H1, H2, H3, etc.), attribut alt pour les images…)<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Les données structurées dont les rich snippets (extraits enrichis)<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; La structure des URLs<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Les temps de chargement<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Le maillage interne<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Les fichiers robots.txt et sitemap.xml<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; La pertinence des mots-clés<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Le placement des mots-clés dans les contenus et leur densité<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Le champ sémantique autour des mots-clés<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; La qualité et l’originalité du contenu<br>
			<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; L’affichage sur mobile (mobile friendly) – Responsive<br>
		</p>
		<p class="blue index1 letter-014" data-aos="flip-left">Ces éléments impactent le référencement naturel d’une page et contribuent à sa bonne indexation par Google.</p>
	<%= image_tag(asset_path('referencement.png'), alt: 'agence marketing web Aix en Provence référencement SEO on-site', class: 'absolute index-1 refrencement-img-page2') %>
</div>

<div class="qu-est-ce-que-le-seo index1 mx-auto relative mb-200" data-aos="zoom-in-up">
	<h2 class="mb-5 h2 text-left black index1">Qu'est que le référencement naturel SEO off-site ?</h2>
	<p class="black-olive index1 letter-014"  data-aos="fade-right">Le référencement naturel off-site, également appelé Netlinking, concerne les éléments extérieurs aux pages web :</p>
	<p class="black-olive index1 letter-014 ml-4"  data-aos="fade-right">
		<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; La popularité du site<br>
		<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Les backlinks (les liens qui pointent vers vos pages en provenance d’autres sites)<br>
		<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Le benchmarck concurrentiel<br>
		<%= image_tag(asset_path('Ellipse-18.svg'), class: 'liste-boule') %>&#160;&#160; Les liens sociaux<br>
	</p>
	<p class="blue index1 letter-014" data-aos="flip-left">Le critérère principal off-page pour Google est la qualité des liens. Il part du principe qu’une page qui plaît aux internautes obtiendra facilement des liens provenant de sites de qualité. 10 backlinks en provenance de quelques sites influents sont plus importants que 100 backlinks venant de sites ayant mauvaise réputation.</p>
	<%= image_tag(asset_path('Ellipse-8.png'), class: 'absolute index-1 cercle-site7') %>
</div>

<%= render "shared/footer" %>
<%= render 'cookies_eu/consent_banner'%>