config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
    }


	constraints(host: /^(?!www\.)/i) do
	    match '(*any)' => redirect { |params, request|
	      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
	    }, :via => :all
 	end

	root to: 'pages#home'

	match "/404", :to => "errors#not_found", :via => :all
	match "/422", :to => "errors#unacceptable", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all

	get '/sitemap.xml' => 'sitemaps#index', :format => 'xml', :as => :sitemap

	get 'robots.:format' => 'pages#robots'
	get 'mentions-legales' => 'pages#mentions_legales'


	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]

	resources :blogs do
		member do
            put "like" => "blogs#upvote"
            put "unlike" => "blogs#unvote"
        end
        resources :comments, :only => [:index, :new, :edit, :create, :update, :destroy] 
	end

	get 'creation-site-internet' => 'services#creation_site_internet'
	get 'referencement' => 'services#referencement'

	mount PolicyManager::Engine => "/policies"

	dynamic_error_pages
  
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	extend FriendlyId
	friendly_id :name, use: :slugged
	acts_as_votable
	has_one_attached :image

	validates :name, uniqueness: true
	validates :meta_title, length: { in: 42..50 }, uniqueness: true
	validates :descriptionindex, length: { in: 131..149 }, uniqueness: true
	validates :image, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_blog, only: [:show, :edit, :update, :destroy, :upvote, :unvote]

  def index
    @blogs = policy_scope(Blog).order(created_at: :desc)
  end

  def show
  end

  def new
    @blog = current_user.blogs.new
    authorize @blog
  end

  def edit
  end


  def create
    @blog = current_user.blogs.new(blog_params)
    authorize @blog
    if @blog.save
      redirect_to @blog, notice: "L'article a bien été créé."
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "L'article a bien été modifié."
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: "L'article a bien été supprimé."
  end

  def upvote
    @blog.liked_by current_user
    redirect_to action: "index"
  end  

  def unvote
    @blog.unliked_by current_user
    redirect_to action: "index"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
    authorize @blog
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:name, :meta_title, :description, :descriptionindex, :image)
  end
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="my-5"><%= f.input :name, label: "Nom :" %></div>
    <div class="my-5"><%= f.input :meta_title, label: "Méta-title : entre 42 et 50 caractères" %></div>
    <div class="my-5"><%= f.input :image, as: :file %></div>
    <div class="my-5"><%= f.input :descriptionindex, label: "Description : entre 131 et 149 caractères" %></div>
    <div class="my-5"><%= f.input :description, input_html: { class: 'tinymce', id: 'description-blog' } %></div>
  </div>


  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary my-5' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<% content_for :meta_title, "Agence marketing web Aix en provence – SEO – site internet" %>
<% content_for :meta_description, "Créez / Optimiser votre site internet, son référencement | Dataweb Univers : agence de marketing web, SEO / SEA et développement à aix en provence – Théo Dumez" %>
<% content_for :meta_robots, "noindex" %>

<%= render "shared/navbar" %>

<div class="articles-index">
	<h1>Editing Blog</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Show', @blog %> |
	<%= link_to 'Back', blogs_path %>
</div>

<%= render "shared/footer" %>

app/views/blogs/index.html.erb
<% content_for :meta_title, "Web Mag – le blog de Dataweb Univers – toutes les news" %>
<% content_for :meta_description, "Découvrez le blog de Dataweb Univers. Nous partageons des ressources et astuces utiles de marketing SEO et site internet pour les développeurs et les entreprises" %>
<% content_for :meta_robots, "index" %>

<script type="application/ld+json" nonce=<%= request.content_security_policy_nonce %>>
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Accueil",
    "item": "<%= root_url %>"
  },{
    "@type": "ListItem",
    "position": 2,
    "name": "Blog",
    "item": "<%= blogs_url %>"
  }]
}
</script>


<%= render "shared/navbar" %>

<div class="articles-index">
  <h1 class="h1 black">Le blog de l'agence web</h1>
  <p class="text-center mx-auto mb-5">Nous partageons des ressources et astuces utiles en marketing web, en SEO et pour les site internet à destination des marketeurs, des développeurs et des entreprises.</p>
  <h2 class="mb-4 mt-5">Les derniers articles :</h2>

  <div class="articles">
    <% if @blogs != nil %>
      <% @blogs.each do |blog| %>

        <div class="article relative mb-5">
          <%= link_to((blog), title: blog.name, class: 'flex') do %>
            <%= cl_image_tag blog.image.key, alt: blog.name, class: 'img-little-blog' %>
          <% end %>
          <%= link_to((blog), title: blog.name) do %>
            <h3 class="mt-4"><%= blog.name %></h3>
          <% end %>
          <p class="black-olive italic font-18"><%= blog.descriptionindex %></p>
          <% if policy(blog).edit? %>
            <%= link_to(edit_blog_path(blog), title: 'éditer', rel: 'nofollow') do %>
             <%= image_tag(asset_path('edit.svg'), alt: 'editer', class: 'img-edit absolute index1') %>
            <% end %>
          <% end %>
          <% if policy(blog).destroy? %>
            <%= link_to(blog, rel: 'nofollow', title: 'supprimer', method: :delete, data: { confirm: 'Vous allez supprimer cet article' }) do %>
              <%= image_tag(asset_path('bin.svg'), alt: 'supprimer', class: 'img-bin absolute index1') %>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            <% if current_user.voted_up_on? blog %>
              <div class="flex flex-row mt-3">
                <%= link_to(unlike_blog_path(blog), method: :put, rel: 'nofollow', title: 'unlike', class: 'nodecoration flex bg-F5F7FB link-like flex-center') do %>
                  <%= image_tag(asset_path('like2.svg'), alt: 'unlike', class: 'img-like') %>
                  <p class="mx-2 font-18 mt-0">J'aime</p>
                  <p class="like-nbr mt-0"><%= blog.votes_for.size %></p>
                <% end %>
                <div class="social-share-button-relative m-0 p-0">
                  <%= social_share_button_tag(blog.name, rel: 'nofollow') %>
                </div>
              </div>
            <% else %>
              <div class="flex flex-row mt-3">
                <%= link_to(like_blog_path(blog), method: :put, rel: 'nofollow', title: 'like', class: 'nodecoration flex bg-F5F7FB link-like flex-center') do %>
                  <%= image_tag(asset_path('like.svg'), alt: 'like', class: 'img-like') %>
                  <p class="mx-2 font-18 mt-0">J'aime</p>
                  <p class="like-nbr mt-0"><%= blog.votes_for.size %></p>
                <% end %>
                <div class="social-share-button-relative m-0 p-0">
                  <%= social_share_button_tag(blog.name, rel: 'nofollow') %>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="flex flex-row mt-3">
              <%= link_to(like_blog_path(blog), method: :put, rel: 'nofollow', title: 'like', class: 'nodecoration flex bg-F5F7FB link-like flex-center') do %>
                <%= image_tag(asset_path('like.svg'), alt: 'like', class: 'img-like') %>
                <p class="mx-2 font-18 mt-0">J'aime</p>
                <p class="like-nbr mt-0"><%= blog.votes_for.size %></p>
              <% end %>
              <div class="social-share-button-relative m-0 p-0">
                <%= social_share_button_tag(blog.name, rel: 'nofollow') %>
              </div>
            </div>
          <% end %>

        </div>
      <% end %>
    <% end %>
  </div>
  <% if policy(Blog).create? %>
    <%= link_to 'nouvel article', new_blog_path, title: 'nouvel article', rel: 'nofollow', class: 'btn btn-outline-primary my-5' %>
  <% end %>
  <% if user_signed_in? == false %>
    <%= link_to 'Se connecter', new_user_session_path, title: 'Se connecter', rel: 'nofollow', class: 'btn btn-outline-secondary m-5' %>
  <% end %>
</div>

<%= render "shared/footer" %>
<%= render 'cookies_eu/consent_banner'%>

app/views/blogs/new.html.erb
<% content_for :meta_title, "Agence marketing web Aix en provence – SEO – site internet" %>
<% content_for :meta_description, "Créez / Optimiser votre site internet, son référencement | Dataweb Univers : agence de marketing web, SEO / SEA et développement à aix en provence – Théo Dumez" %>
<% content_for :meta_robots, "noindex" %>

<%= render "shared/navbar" %>

<div class="articles-index">
	<h1>Nouvel Article</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Back', blogs_path %>
</div>

<%= render "shared/footer" %>

app/views/blogs/show.html.erb
<% content_for :meta_title, "Web Mag – #{@blog.meta_title}" %>
<% content_for :meta_description, "#{@blog.descriptionindex}" %>
<% content_for :meta_robots, "index" %>

<script type="application/ld+json" nonce=<%= request.content_security_policy_nonce %>>
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Accueil",
    "item": "<%= root_url %>"
  },{
    "@type": "ListItem",
    "position": 2,
    "name": "Blog",
    "item": "<%= blogs_url %>"
  },{
    "@type": "ListItem",
    "position": 3,
    "name": "<%= @blog.name %>",
    "item": "<%= blog_url(@blog) %>"
  }]
}
</script>

<script type="application/ld+json" nonce=<%= request.content_security_policy_nonce %>>
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "<%= @blog.name %>",
  "image": "<%= @blog.image.key %>",
  "datePublished": "<%= @blog.created_at.strftime("%Y-%m-%d") %>",
  "dateModified": "<%= @blog.updated_at.strftime("%Y-%m-%d") %>",
  "creator": "Dataweb Univers",
  "author": "Dataweb Univers",
  "articleBody": "<%= @blog.descriptionindex.first(100) %>...",
  "mainEntityOfPage": "True"
}
</script>

<%= render "shared/navbar" %>

<h1 class="h1 black letter-009 mx-5">
  <%= @blog.name %>
</h1>
<div class="articles-index flex flex-row">
	<div class="blog-show relative">
		<div class="image-like_partage flex justify-content-center align-items-center">
			<%= cl_image_tag(@blog.image.key, alt: @blog.name, class: 'img-blog_view my-4 mx-auto') %>
		</div>

		<div class="description-blog my-4">
			<%= @blog.description.html_safe %>
		</div>

    <% if user_signed_in? %>
      <% if current_user.voted_up_on? @blog %>
        <div class="flex flex-row mt-3">
          <%= link_to(unlike_blog_path(@blog), method: :put, rel: 'nofollow', title: 'unlike', class: 'nodecoration flex bg-F5F7FB link-like flex-center') do %>
            <%= image_tag(asset_path('like2.svg'), alt: 'unlike', class: 'img-like') %>
            <p class="mx-2 font-18 mt-0">J'aime</p>
            <p class="like-nbr mt-0"><%= @blog.votes_for.size %></p>
          <% end %>
          <div class="social-share-button-relative m-0 p-0">
            <%= social_share_button_tag(@blog.name, rel: 'nofollow') %>
          </div>
        </div>
      <% else %>
        <div class="flex flex-row mt-3">
          <%= link_to(like_blog_path(@blog), method: :put, rel: 'nofollow', title: 'like', class: 'nodecoration flex bg-F5F7FB link-like flex-center') do %>
            <%= image_tag(asset_path('like.svg'), alt: 'like', class: 'img-like') %>
            <p class="mx-2 font-18 mt-0">J'aime</p>
            <p class="like-nbr mt-0"><%= @blog.votes_for.size %></p>
          <% end %>
          <div class="social-share-button-relative m-0 p-0">
            <%= social_share_button_tag(@blog.name, rel: 'nofollow') %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="flex flex-row mt-3">
        <%= link_to(like_blog_path(@blog), method: :put, rel: 'nofollow', title: 'like', class: 'nodecoration flex bg-F5F7FB link-like flex-center') do %>
          <%= image_tag(asset_path('like.svg'), alt: 'like', class: 'img-like') %>
          <p class="mx-2 font-18 mt-0">J'aime</p>
          <p class="like-nbr mt-0"><%= @blog.votes_for.size %></p>
        <% end %>
        <div class="social-share-button-relative m-0 p-0">
          <%= social_share_button_tag(@blog.name, rel: 'nofollow') %>
        </div>
      </div>
    <% end %>

		<% if policy(@blog).edit? %>
      <%= link_to(edit_blog_path(@blog), title: 'éditer', rel: 'nofollow') do %>
       <%= image_tag(asset_path('edit.svg'), alt: 'editer', class: 'img-edit absolute index1') %>
      <% end %>
    <% end %>
    <% if policy(@blog).destroy? %>
      <%= link_to(@blog, rel: 'nofollow', title: 'supprimer',method: :delete, data: { confirm: 'Vous allez supprimer cet article' }) do %>
        <%= image_tag(asset_path('bin.svg'), alt: 'supprimer', class: 'img-bin absolute index1') %>
      <% end %>
    <% end %>
		<%= link_to 'Retour', blogs_path, class: 'btn btn-outline-primary my-5' %>
	</div>
	<div class="blog-autres ml-4">
    <div class="carre-design ml-4">
  		<div class="carre-partage my-5">
          <div class="partager flex flex-center">
            <h2>Partagez</h2>
          </div>
          <div class="liens-partage flex flex-center">
            <%= social_share_button_tag(@blog.name, rel: 'nofollow') %>
          </div>
          <div class="newletter flex flex-column flex-center">
            <%= link_to((new_user_registration_path), title: "S’inscrire à la newsletter", rel: "nofollow", class: "btn-newletter") do %>
              <p class="black-olive m-0 font-18">S’inscrire à la newsletter</p>
            <% end %>
            <p class="white m-0 font-16">Inscription rapide et gratuite</p>
          </div>
      </div>
      <div class="carre-partage my-5">
        <p class="blue italic font-18 mx-3 line-height-116">Rédaction</p>
        <p class="black font-18 text-800 mx-3 line-height-116">Besoin d’un rédacteur pour créer ou optimiser vos contenus web ?</p>
        <p class="black-olive font-18 mx-3 line-height-116">Contactez-nous pour commander rapidement vos textes</p>
        <%= link_to((contacts_path), title: "Contactez-nous", rel: "nofollow", class: "flex-around mt-4") do %>
          <%= image_tag(asset_path('arrow.svg'),alt: 'Flèche Rédaction', class: 'img-arrow-blog') %>
          <%= image_tag(asset_path('wall_post.svg'),alt: 'Contactez-nous Rédaction', class: 'img-contact-show-blog') %>
        <% end %>
      </div>
       <div class="carre-partage my-5">
        <p class="blue italic font-18 mx-3 line-height-116">Graphisme</p>
        <p class="black font-18 text-800 mx-3 line-height-116">Logo,<br>Webdesign,<br>Identité visuelle</p>
        <p class="black-olive font-18 mx-3 line-height-116">Contactez-nous pour recevoir un devis</p>
        <%= link_to((contacts_path), title: "Contactez-nous", rel: "nofollow", class: "flex-around mt-4") do %>
          <%= image_tag(asset_path('arrow.svg'),alt: 'Flèche Rédaction', class: 'img-arrow-blog') %>
          <%= image_tag(asset_path('design_thinking.svg'),alt: 'Contactez-nous Rédaction', class: 'img-contact-show-blog') %>
        <% end %>
      </div>
       <div class="carre-partage my-5">
        <p class="blue italic font-18 mx-3 line-height-116">Référencement</p>
        <p class="black font-18 text-800 mx-3 line-height-116">Besoin d’un expert SEO / SEA ?</p>
        <p class="black-olive font-18 mx-3 line-height-116">Contactez-nous pour une meilleure position sur Google</p>
        <%= link_to((contacts_path), title: "Contactez-nous", rel: "nofollow", class: "flex-around mt-4") do %>
          <%= image_tag(asset_path('arrow.svg'),alt: 'Flèche Rédaction', class: 'img-arrow-blog') %>
          <%= image_tag(asset_path('design_data.svg'),alt: 'Contactez-nous Rédaction', class: 'img-contact-show-blog') %>
        <% end %>
      </div>
    </div> 
	</div>
</div>
<div class="w-80 mx-auto">
  <% if user_signed_in? == false %>
    <%= link_to 'Se connecter', new_user_session_path, title: 'Se connecter', rel: 'nofollow', class: 'btn btn-outline-secondary my-5' %>
  <% end %>
</div>
<%= render partial: "comments/index" %>
<%= render "shared/footer" %>
<%= render 'cookies_eu/consent_banner'%>