config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
    }


	constraints(host: /^(?!www\.)/i) do
	    match '(*any)' => redirect { |params, request|
	      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
	    }, :via => :all
 	end

	root to: 'pages#home'

	match "/404", :to => "errors#not_found", :via => :all
	match "/422", :to => "errors#unacceptable", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all

	get '/sitemap.xml' => 'sitemaps#index', :format => 'xml', :as => :sitemap

	get 'robots.:format' => 'pages#robots'
	get 'mentions-legales' => 'pages#mentions_legales'


	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]

	resources :blogs do
		member do
            put "like" => "blogs#upvote"
            put "unlike" => "blogs#unvote"
        end
        resources :comments, :only => [:index, :new, :edit, :create, :update, :destroy] 
	end

	get 'creation-site-internet' => 'services#creation_site_internet'
	get 'referencement' => 'services#referencement'

	mount PolicyManager::Engine => "/policies"

	dynamic_error_pages
  
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog
	belongs_to :user

	extend FriendlyId
	friendly_id :comment, use: :slugged
	
	validates :comment, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index]

  before_action :set_blog, only: [:new, :create, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end


  def new
    @comment = @blog.comments.new
    @comment.user = current_user
    authorize @comment
  end

  def edit
    @blog = Blog.friendly.find(params[:blog_id])
    @comment = @blog.comments.friendly.find(params[:id])
    authorize @comment
  end

  def create
    @comment = @blog.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment
    if @comment.save
      redirect_to blog_path(@blog), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    @comment = @blog.comments.new(comment_params)
    @comment.user = current_user
    authorize @comment
    if @comment.update(comment_params)
      redirect_to blog_path(@blog), notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.friendly.find(params[:blog_id])
    @comment = @blog.comments.friendly.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to blog_path(@blog), notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:blog_id])
    end

    def set_comment
      @blog = Blog.friendly.find(params[:blog_id])
      @comment = @blog.comments.friendly.find(params[:id])
      authorize @comment
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/views/comments/_form.html.erb
<%= simple_form_for([@blog, @comment]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :comment, label: 'Commentaire :' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<div class="commentaires bg-F5F7FB">
  <div class="commentaires-index">
    <h3 class="mx-5 mt-3 mb-5">Commentaires :</h3>
    <% if @blog.comments != nil %>
      <% if @blog.comments.size > 0 %>
        <% @blog.comments.each do |comment| %>
          <div class="comment-box py-4 mb-5 flex flex-column relative">
            <div class="flex flex-row">
              <p class="mr-3 mt-0 font-18"><strong><%= comment.user.nom %></strong></p>
              <p class="mt-0 font-18"><%= comment.created_at.strftime("Le %d/%m/%Y à %Hh%M") %></p>
            </div>
            <p class="font-18 color-616671 mx-2"><%= comment.comment %></p>
            <% if policy(comment).edit? %>
              <%= link_to(edit_blog_comment_path(@blog, comment), title: 'éditer', rel: 'nofollow') do %>
               <%= image_tag(asset_path('edit.svg'), alt: 'editer', class: 'img-edit absolute index1') %>
              <% end %>
            <% end %>
            <% if policy(comment).destroy? %>
              <%= link_to(blog_comment_path(@blog, comment), rel: 'nofollow', title: 'supprimer', method: :delete, data: { confirm: 'Vous allez supprimer cet article' }) do %>
                <%= image_tag(asset_path('bin.svg'), alt: 'supprimer', class: 'img-bin absolute index1') %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p class="font-18 color-616671 mx-2 mt-0 mb-4">Il n'y a pas de Commentaires pour l'instant</p>
      <% end %>
    <% end %>
    <% if policy(Comment).new? %>
      <%= link_to('écrire un commentaire', new_blog_comment_path(@blog), rel: 'nofollow', title: 'écrire un commentaire', class: "btn btn-outline-primary mt-3") %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<% content_for :meta_title, "Agence marketing web Aix en provence – SEO – site internet" %>
<% content_for :meta_description, "Créez / Optimiser votre site internet, son référencement | Dataweb Univers : agence de marketing web, SEO / SEA et développement à aix en provence – Théo Dumez" %>
<% content_for :meta_robots, "noindex" %>

<%= render "shared/navbar" %>

<div class="articles-index">
	<h1>Editer le commenaire</h1>

	<%= render 'form', comment: @comment %>

	<%= link_to 'Retour', @blog, class: 'btn btn-outline-secondary mt-4' %>
</div>

<%= render "shared/footer" %>

app/views/comments/new.html.erb
<% content_for :meta_title, "Agence marketing web Aix en provence – SEO – site internet" %>
<% content_for :meta_description, "Créez / Optimiser votre site internet, son référencement | Dataweb Univers : agence de marketing web, SEO / SEA et développement à aix en provence – Théo Dumez" %>
<% content_for :meta_robots, "noindex" %>

<%= render "shared/navbar" %>

<div class="articles-index">
	<h1>Nouveau commentaire</h1>

	<%= render 'form', comment: @comment %>

	<%= link_to 'Retour', blog_path(@blog), class: 'btn btn-outline-secondary mt-4' %>
</div>

<%= render "shared/footer" %>