config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
    }


	constraints(host: /^(?!www\.)/i) do
	    match '(*any)' => redirect { |params, request|
	      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
	    }, :via => :all
 	end

	root to: 'pages#home'

	match "/404", :to => "errors#not_found", :via => :all
	match "/422", :to => "errors#unacceptable", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all

	get '/sitemap.xml' => 'sitemaps#index', :format => 'xml', :as => :sitemap

	get 'robots.:format' => 'pages#robots'
	get 'mentions-legales' => 'pages#mentions_legales'


	match '/contacts',     to: 'contacts#new',             via: 'get'
	resources "contacts", only: [:new, :create]

	resources :blogs do
		member do
            put "like" => "blogs#upvote"
            put "unlike" => "blogs#unvote"
        end
        resources :comments, :only => [:index, :new, :edit, :create, :update, :destroy] 
	end

	get 'creation-site-internet' => 'services#creation_site_internet'
	get 'referencement' => 'services#referencement'

	mount PolicyManager::Engine => "/policies"

	dynamic_error_pages
  
end

app/views/shared/_banner-text.html.erb
<div class="w50 flex-center index1">
	<div class="banner-text">
		<div class="rotating-text mt-4">
			<h1 class="rb-55 blue h1 text-center ml12 max-700">Agence marketing web Aix-en-provence</h1>
			<p class="font-35 rt-25 rotating-text-word">
		        <span class="word black">améliorez &#160; un &#160; site &#160; existant</span>
		        <span class="word black">améliorez &#160; votre &#160; référencement</span>
		        <span class="word black">créez &#160; votre &#160; site &#160; web</span>
	    	</p>
	    	<p class="font-35 rt-25 rotating-text-p black">améliorez un site existant</p>
		    <p class="font-35 rt-25 rotating-text-p black">augmentez votre référencement</p>
		    <p class="font-35 rt-25 rotating-text-p black">créez votre site web</p>
	    	<div class="vide"></div>
		    <p class="rouge-font font-30 rt-80 rl-20">
		    	Propulsez-vous dans<br>
		    	l’univers du web
		    </p>
		</div>
	</div>
</div>

app/views/shared/_banner.html.erb
<div class="banner relative index1">
    <%= render "shared/banner-text" %>
    <div class="flex-center index1 img-banner-section">
    	<%= image_tag(asset_path('digital-marketing-illustration.png'), alt: 'communication web illustration', class: 'img-banner') %>
    </div>
    <%= image_tag(asset_path('Vector-4.png'), class: 'background-vector-img index0') %>
    <%= image_tag(asset_path('rocket-ellipse.png'), class: 'rocket-ellipse-img index0') %>
    <%= image_tag(asset_path('Ellipse-8.png'), class: 'ellipse8-img index0') %>
    <%= image_tag(asset_path('blue-cercle.svg'), class: 'cercle-banner1 index1 bleu-cercle-banner') %>
    <%= image_tag(asset_path('blue-cercle.svg'), class: 'cercle-banner2 index1 bleu-cercle-banner') %>
    <%= image_tag(asset_path('blue-cercle.svg'), class: 'cercle-banner3 index1 bleu-cercle-banner') %>
</div>

app/views/shared/_confiance.html.erb
<div class="swiper-container mt-5">
  <div class="swiper-wrapper">
    <div class="swiper-slide"><%= image_tag(asset_path('logo-ophtalmo-miramas.png'), alt: 'agence marketing web aix-en-Provence client site internet et référencement ophtalmo-miramas', class: 'logo-confiance') %></div>
    <div class="swiper-slide"><%= image_tag(asset_path('logo-renovbardage-png.jpg'), alt: 'agence marketing web aix-en-Provence client site internet et référencement renov-bardage', class: 'logo-confiance') %></div>
    <div class="swiper-slide"><%= image_tag(asset_path('logo-francecbd.png'), alt: 'agence marketing web aix-en-Provence client site internet et référencementophtalmo-miramas', class: 'logo-confiance') %></div>
    <div class="swiper-slide"><%= image_tag(asset_path('logo-coiffure.png'), alt: 'agence marketing web aix-en-Provence client site internet et référencement ophtalmo-miramas', class: 'logo-confiance') %></div>
    <div class="swiper-slide"><%= image_tag(asset_path('logo-imall-industrie.png'), alt: 'agence marketing web aix-en-Provence client site internet et référencement ophtalmo-miramas', class: 'logo-confiance') %></div>
    <div class="swiper-slide"><%= image_tag(asset_path('logo-bailti.png'), alt: 'agence marketing web aix-en-Provence client site internet et référencement ophtalmo-miramas', class: 'logo-confiance') %></div>
  </div>
  <!-- Add Pagination -->
  <div class="swiper-pagination"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="presentation flex-center bg-khaki flex-column">
	<div class="h1-container">
		<h2 class="h2 black m-0">
			L'agence de Web marketing à Aix en provence
		</h2>
	</div>
	<div class="cent80 flex-around mb-3">
		<p class="self-start ml-4 mt-4 black">
			Dans le Web, la stratégie digitale est essentielle. C’est le fondement de votre réussite.<br>
			Contactez-nous pour créer des sites web engageants et optimisés pour le référencement<br>
		</p>
		<%= image_tag(asset_path('growth.svg'), alt: 'icone croissance', class: 'growth-icon') %>
	</div>
</div>
<div class="footer flex-center bg-khaki py-5">
	<div class="logo flex-column mr5">
		<%= image_tag(asset_path('Growth-marketing.png'), alt: 'logo data web univers footer', class: 'img_footer') %>
	</div>
	<div class="contactez-nous flex-column ml5">
		<h2>Contactez-nous</h2>
		<p>Théo Dumez</p>
		<%= link_to((contacts_path), title: "Contactez-nous", rel: "nofollow") do %>
			<p class="mail-black">Contactez-nous</p>
		<% end %>
		<p>06.43.42.46.07</p>
	</div>
</div>
<div class="footer flex-center bg-khaki py-2 flex-column">
	<div class="ligne"></div>
	<p class="font-16 footer-text text-center"> © 2020 Dataweb Univers | Théo Dumez | Agence webmarketing et référencement Aix-en-Provence Marseille | <%= link_to "Mentions légales", mentions_legales_path, title: "Mentions légales" %> | Tous droits réservés</p>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
	<div class="admin-bar">
		<div class="flex-between w-80">
			<p class="mx-4 mt-0 font-16 color-7e828e">Bienvenue <%= "#{current_user.nom}" %></p>
			<p class="mx-4 mt-0 font-16"><%= link_to "Se déconnecter", destroy_user_session_path, class: 'mx-4', method: :delete, data: { confirm: 'Vous allez vous déconnecter' } %></p>
		</div>
	</div>
<% end %>
<div class='navbar'>
	<div class="flex-center">
		<div class='logo'>
			<%= link_to((root_path), title: "Accueil") do %>
				<%= image_tag(asset_path('Growth-marketing.png'), alt: 'agence marketing web Aix en provence Dataweb Univers logo', class: 'img_navbar mr-3') %>
			<% end %>
		</div>
		<%= link_to((root_path), title: "Accueil", class: 'nodecoration') do %>
			<p class="ml-5"><span class="black-olive">Data</span><span class="teel">Web</span> <span class="blue">Univers</span></p>
		<% end %>
	</div>
	<div class='nav-links navbar-expand-lg'>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <%= image_tag(asset_path('menu.svg'), alt: 'agence marketing web Aix en provence Dataweb Univers menu', class: 'navbar-toggler-icon') %>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<%= link_to((blogs_path), title: "Blog", class: 'nodecoration referencement-link') do %>
						<p class="mx-4 taupe blog-link referencement-link">Blog</p>
					<% end %>
				</li>
				<li>
					<%= link_to((contacts_path), title: "Contactez-nous", rel: "nofollow contact-mail") do %>
						<p class="mx-4 teel mail">Contactez-nous</p>
					<% end %>
				</li>
				<li class="nav-item active">
					<div class="dropdown">
						<%= link_to((root_path), title: "Nos-services", class: 'nodecoration dropdown-toggle mx-4 flex-center service-down', href: "#", "role": "button", id: "dropdownMenuLink", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false") do %>
							<p class="taupe service-text service-down">Nos services</p>
						<% end %>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<%= link_to((referencement_path), title: "Référencement (SEO/SEA)", class: 'dropdown-item') do %>
								<p class="taupe service-text referencement-link">Référencement</p>
							<% end %>
							<%= link_to((creation_site_internet_path), title: "Création de site internet", class: 'dropdown-item') do %>
								<p class="taupe service-text creation-link">Création de site internet</p>
							<% end %>
						</div>
					</div>
				</li>
				<li class="nav-item active">
					<p class="mx-4 blue telephone">Théo Dumez</p>
				</li>
			</ul>
		</div>
	</div>
</div>